<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-12-30 10:41

$extensionClassesPath = t3lib_extMgm::extPath('ter_doc') . 'Classes/';
return array(
	'tx_terdoc_utility_cli' => t3lib_extMgm::extPath('ter_doc').'Classes/Utility/Cli.php',
	'tx_terdoc_controller_clicontroller' => t3lib_extMgm::extPath('ter_doc').'Classes/Controller/CliController.php',
	'tx_terdoc_domain_repository_extensionrepository' => t3lib_extMgm::extPath('ter_doc').'Classes/Domain/Repository/ExtensionRepository.php',
	'tx_terdoc_validator_environment' => t3lib_extMgm::extPath('ter_doc').'Classes/Validator/Environment.php',
);
?>